### ISSUE TITLE
[FIX] 인증코드 부여방식 링크가 아닌 직접 입력방식 추가하기 

### ISSUE THREAD

**Issue by JunHyungJang** [connetist/connectist-backend#155]
## 📕 제목
인증코드 부여방식 링크가 아닌 직접 입력으로 바꾸기 
## 📔 설명
링크를 통해서 인증코드를 확인하는 방법은 매우 편한 방식입니다. 
하지만 현재 api-gateway에서 cookie의 port번호를 이용하여 routing을 진행하고 있습니다. 
만약 인증을 보낸 브라우저와 사용자가 사용하고있는 브라우저가 다르면 cookie를 활용할 수 가 없습니다
-> 대부분 chrome을 이용하여 access할것으로 예상되기 때문에 cookie를 사용할 수는 있을겁니다 

테스트를 할때는 근데 브라우저가 다르기 때문에 postman에서 확인하기 어려운 단점이 있는거같습니다

기존의 방식은 그대로 두고, 직접입력방식을 추가해주셨으면 합니다 
## 🏫 To-do
- [x] 인증코드 직접입력 방식으로 추가하기

**Comment by hyojaeKwon** [comment]
확인했습니다
