### ISSUE TITLE
[FIX] 최초 회원가입 시 유저 null 현상 해결

### ISSUE THREAD

**Issue by hyojaeKwon** [connetist/connectist-backend#26]
## 📕 제목
최초 회원가입 시 유저 null 현상 해결

## 📔 내용
최초 회원가입을 위한 post요청을 보내면 userCreate가 null이 되는 현상이 있는데 이를 해결하고 handling합니다.

## 🏫 To-do
- [ ] Error Handling구현
- [ ] 버그 현상 제거

**Comment by JunHyungJang** [comment]
제목에 내용을 쓰지말고, 제목 밑에 내용써주세요

**Comment by hyojaeKwon** [comment]
수정하였습니다!
