### ISSUE TITLE
[FIX] Controller 에 대한 고찰

### ISSUE THREAD

**Issue by JunHyungJang** [connetist/connectist-backend#39]
## 📕 제목
Controller에 대한 고찰 
## 📔 설명
Controller 를 개발하면서 봉착한 문제 공유

<img width="772" alt="image" src="https://github.com/connetist/connectist-backend/assets/89409079/28c2f69f-8397-4a4c-b86d-c0242e69f1d9">

1. Controller를 통해서 CRUD를 할때 Return값은 어떻게 할것인가?
 - Create를 하면 Domain을 반환?
 - Delete 하면 Void or Domain?
 - Get를 하면 해당 객체를 반환하는것은 자명한 사실 
 - 따라서 Get 요청 이외의 것들에 대한 return 값 의논

2. 유효성 검사
 - 만약 Request parameter가 잘못되었을 경우에 어디서 유효성을 검사하는가? controller or service?( 컨트롤러가 맞는거같긴한데 추후 의논 필요)
3. 에러처리
 - 공통적인 에러에 대한 같은 템플릿을 하나 만들어야할것같음 

## 🏫 To-do
- [x] Controller return값
- [x] 유효성검사
- [x] 에러처리

**Comment by hyojaeKwon** [comment]
1번은 frontend와 같이 고민할 필요가 있을 것 같습니다.
2번은 controller라고 생각합니다. service layer에는 비즈니스로직과 관련된 부분이 들어가야할 것 같고, request param같은 단순한 api호출 예외를 다루는 부분은 controller에서 처리하는 것으로 통일하는게 좋을 것 같습니다.
3번은 마음 깊은 곳에서 동의하고 있습니다ㅎㅎㅎ

**Comment by hyojaeKwon** [comment]
1번은 frontend에서 제공받아야하는 정보에 따라 dto를 구성하고 ResponseEntity의 body로 넣어 반환하는게 좋을 것 같습니다.
