### ISSUE TITLE
[FEAT] 예외처리에 대한 고민

### ISSUE THREAD

**Issue by hyojaeKwon** [connetist/connectist-backend#48]
## 📕 제목
예외처리에 대한 고민

## 📔 설명
- 다양한 상황에 대한 **유연한** 예외 처리 방법을 고민한다.
- 사전에 예외를 방지할 수 있는 **통일된** 방법을 고민한다.
- 사용자에게 예외 상황에 대한 충분한 정보를 제공한다.

### 예상할 수 있는 예외 상황 (더 검토해봐야 합니다.)
1. 잘못된 uri
2. 잘못된 parameter value(ex, null)
3. service logic 수행 중 발생하는 예외

### 예외 처리 방법
1. 각 상황에 대하여 Enum으로 HttpStatus와 error msg를 관리한다.
2. 각 서비스 별 custom exception class를 만든다. (user-service의 경우 user.util.exception 패키지 내)
3. service layer에서 business logic를 수행하다가 exception이 생기면 해당 클래스를 통해 exception을 throw한다.
4. controller에 GlobalExceptionAdvice인 exception handler를 만들고, ErrorResponse용 객체를 통해 사용자에게 반환한다.

### 현재 상황
1. 사용자가 보낸 값의 유효성을 검증하는 로직이 없습니다.
2. exception handler에서 제공하는 정보가 한정적입니다.
3. exception handling위치 및 방법이 통일되어있지 않습니다.

같이 고민해보면 좋겠습니다. 

## 🏫 참고 사항
- [좋은 예외 로직에 대해서](https://jojoldu.tistory.com/734)

**Comment by JunHyungJang** [comment]
내일만나서 이야기합죠
